# Generated by Django 2.2.6 on 2020-07-14 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_shares', models.CharField(max_length=254)),
                ('mobile_no', models.CharField(max_length=254)),
                ('sh_fname', models.CharField(max_length=254)),
                ('sh_lname', models.CharField(max_length=254)),
                ('sh_mname', models.CharField(blank=True, max_length=254)),
                ('sh_email', models.CharField(max_length=254)),
                ('sh_position', models.CharField(blank=True, max_length=254)),
                ('company_images', models.FileField(upload_to='Media_Files/StockHolder_Profile_Picture')),
                ('sh_proxy_fname', models.CharField(blank=True, max_length=254)),
                ('sh_proxy_lname', models.CharField(blank=True, max_length=254)),
                ('sh_proxy_mname', models.CharField(blank=True, max_length=254)),
                ('sh_proxy_email', models.CharField(blank=True, max_length=254)),
                ('sh_date_added', models.DateTimeField(auto_now_add=True)),
                ('sh_password_status', models.CharField(blank=True, max_length=254)),
                ('sh_account_status', models.CharField(blank=True, max_length=254)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=254)),
                ('sh_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
