# Generated by Django 2.2.6 on 2020-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockholder',
            name='sh_account',
        ),
        migrations.AlterField(
            model_name='stockholder',
            name='sh_mname',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='stockholder',
            name='sh_position',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='stockholder',
            name='sh_proxy_fname',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='stockholder',
            name='sh_proxy_lname',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='stockholder',
            name='sh_proxy_mname',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
