# Generated by Django 2.2.6 on 2020-07-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholder',
            name='sh_classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockholder',
            name='sh_proxy_status',
            field=models.BooleanField(default=False),
        ),
    ]
