# Generated by Django 2.2.6 on 2020-07-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0002_stockholder_sh_proxy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholder',
            name='sh_proxy_status',
            field=models.BooleanField(blank=True),
        ),
    ]
