# Generated by Django 2.2.6 on 2020-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0002_auto_20200703_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholder',
            name='sh_account',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
