# Generated by Django 2.2.6 on 2020-07-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0003_stockholder_sh_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholder',
            name='sh_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
