# Generated by Django 2.2.6 on 2020-07-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0003_auto_20200714_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholder',
            name='sh_proxy_status',
            field=models.BooleanField(default=False),
        ),
    ]
