# Generated by Django 2.2.6 on 2020-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0004_auto_20200714_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholder',
            name='sh_classification',
            field=models.BooleanField(default=False),
        ),
    ]
