# Generated by Django 2.2.6 on 2020-07-03 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0005_stockholder_sh_password_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholder',
            name='sh_account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
