# Generated by Django 2.2.6 on 2020-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0008_auto_20200704_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholder',
            name='company_images',
            field=models.FileField(upload_to='Media_Files/StockHolder_Profile_Picture'),
        ),
    ]
