# Generated by Django 2.2.6 on 2020-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0009_auto_20200704_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholder',
            name='sh_account_status',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
