# Generated by Django 2.2.6 on 2020-07-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0010_stockholder_sh_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
