# Generated by Django 2.2.6 on 2020-07-13 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_newstockholder', '0011_stockholder_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholder',
            name='mobile_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockholder',
            name='sh_proxy_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='stockholder',
            name='sh_shares',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockholder',
            name='updated_by',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
