# Generated by Django 2.2.6 on 2020-07-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.CharField(max_length=255)),
                ('election_code', models.CharField(max_length=255)),
                ('sh_fullname', models.CharField(max_length=255)),
                ('sh_email', models.CharField(max_length=255, null=True)),
                ('sh_shares', models.CharField(max_length=255, null=True)),
                ('at_status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
                ('code', models.CharField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.CharField(max_length=255)),
                ('election_code', models.CharField(max_length=255)),
                ('sh_fullname', models.CharField(max_length=255)),
            ],
        ),
    ]
