# Generated by Django 3.0.8 on 2020-07-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_votemaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='added_by',
        ),
    ]
