# Generated by Django 2.2.6 on 2020-07-16 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_votemaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='election_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nominee',
            name='company_images',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Media_Files/StockHolder_Profile_Picture'),
            preserve_default=False,
        ),
    ]
