# Generated by Django 3.0.8 on 2020-07-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_votemaster', '0002_remove_election_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.CharField(max_length=255)),
                ('election_code', models.CharField(max_length=255)),
                ('sh_fullname', models.CharField(max_length=255)),
            ],
        ),
    ]
