# Generated by Django 3.0.8 on 2020-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_votemaster', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='at_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
