# Generated by Django 2.2.6 on 2020-07-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_votemaster', '0004_attendance_at_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.CharField(max_length=255)),
                ('election_code', models.CharField(max_length=255)),
                ('sh_fullname', models.CharField(max_length=255)),
            ],
        ),
    ]
