# Generated by Django 3.0.8 on 2020-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_votemaster', '0006_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='target_date',
            field=models.DateField(null=True),
        ),
    ]
