# Generated by Django 2.2.6 on 2020-07-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eballot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eballot',
            name='remain_vote',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eballot',
            name='vote_allocated',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockholdervote',
            name='eballot_num',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockholdervote',
            name='election_code',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
