# Generated by Django 2.2.6 on 2020-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eballot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eballot',
            name='election_code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='eballotbatch',
            name='eballot_batch_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='eballotnum',
            name='eballot_num',
            field=models.CharField(max_length=250),
        ),
    ]
