# Generated by Django 2.2.6 on 2020-07-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eballot', '0002_auto_20200716_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='eballot',
            name='company_images',
            field=models.FileField(default=0, upload_to='Media_Files/StockHolder_Profile_Picture'),
            preserve_default=False,
        ),
    ]
