# Generated by Django 2.2.6 on 2020-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eballot', '0003_eballot_company_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eballot',
            name='sh_id',
            field=models.CharField(max_length=250),
        ),
    ]
