# Generated by Django 2.2.6 on 2020-07-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eballot', '0002_auto_20200710_2354'),
        ('eballot', '0004_auto_20200716_1127'),
    ]

    operations = [
    ]
